### ISSUE TITLE
Keep getting "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

### ISSUE THREAD

**Issue by kostyay** [Ramilito/kubesess#11]
**Describe the bug**
I seem to be getting this error trying to switch to namespaces/context once in a while.
First time I deleted the cache and it fixed the issue, now I'm getting it on one of the environments I work on.
How can I debug the issue?

```
> kn xxxx
> kgpo
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I dont even have any clusters on localhost:8080 so not sure what it wants

**Comment by Ramilito** [comment]
You would look at the $KUBECONFIG env variable. That has to be set to your kubernetes config (home/user/.kube/config)
So if it gives error right away then the issue is probably there.

If you use it for a while and then get an error, that would probably be a bug.

You would debug it the same way, print out the $KUBECONFIG env, it should look something like this:
```
/home/ramilito/.kube/kubesess/cache/CLUSTERNAME:/home/ramilito/.kube/config
```
Take a look at that added file, the error would be in it

**Comment by kostyay** [comment]
```
>>>echo $KUBECONFIG
/Users/kostyay/.kube/kubesess/cache/XXXX:/Users/kostyay/.kube/config
```

```
cat -p /Users/kostyay/.kube/kubesess/cache/XXX
kind: Config
apiVersion: v1
current-context: XXXX
kind: Config
apiVersion: v1
current-context: XXXX
contexts:
- context:
    namespace: dkron
    cluster: XXXX
    user: XXXX
  name: XXXX
```

Does the config look fine? seems like it contains duplicate lines
