### ISSUE TITLE
Namespace per session

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubesess#35]
**Is your feature request related to a problem? Please describe.**

At the moment only context is handled per session, is it possible to handle namespace the same way?

**Describe the solution you'd like**

A way to make namespace sticky for that session only

**Comment by eshepelyuk** [comment]
Hello 

Is there any news about this feature ?

I am experiencing the same problem, when opening two panes/tabs - and using `kn` alias.
The namespace switch applies to both panes, because the merge KUBECONFIG path context specific and not login session specific, so the path is the same for both shells.

**Comment by Ramilito** [comment]
Hi! Haven't had time to work on this but thanks for bumping it, focusing mostly on kubectl.nvim this week but maybe next week!

**Comment by eshepelyuk** [comment]
Hello @Ramilito 

Thanks for asnwering. It would be great if this project get some fresh improvements. I've migrated recently from kubect / kubens and this tool is exactly what is needed: fast and flexible, no way back.

I hope it wouldn't be abandoned and will keep receiving updates and improvements.

**Comment by Ramilito** [comment]
Yeah I've been planning on a bit of a rewrite on some parts to enable the implementation of some features, this namespace per session is one of them! 
I use this tool all the time as well so no worries on dropping it 👍  and thank you for the encouragement ❤️

**Comment by Ramilito** [comment]
@eshepelyuk This is done now, created a new release, unfortunatelly the changes were huge and the testing I did is only on my machine so there could still be bugs, please let me know if you find any issues! Also, there are breaking changes that need to be sorted out when you upgrade. You can read more in the [release page](https://github.com/Ramilito/kubesess/releases/tag/2.0.0)

**Comment by eshepelyuk** [comment]
Hello @Ramilito 
Those are great news, will this release be propagated to Homebrew ?

**Comment by Ramilito** [comment]
Yes! There is a PR up for brew here: https://github.com/Homebrew/homebrew-core/pull/195053
The github action didn't work last night but successfully worked now so should be available when the PR is merged.

**Comment by eshepelyuk** [comment]
Great, waiting for merge :)

**Comment by Ramilito** [comment]
@eshepelyuk It's merged!

**Comment by Ramilito** [comment]
hmm, tried adding a dash into mine and it worked, could you share the kubeconfig file? please delete all the sensitive information before that 🙏

**Comment by eshepelyuk** [comment]
> hmm, tried adding a dash into mine and it worked, could you share the kubeconfig file? please delete all the sensitive information before that 🙏

Why dash ? I mentioned slash - `/`

**Comment by Ramilito** [comment]
mb, I ment slash!

**Comment by eshepelyuk** [comment]
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX
    server: XXX
  name: arn:aws:eks:xxx:XXX:cluster/d-dev
- cluster:
    certificate-authority-data: XXX
    server: https://0.0.0.0:37771
  name: k3d-del-local
contexts:
- context:
    cluster: arn:aws:eks:XXX:XXX:cluster/d-dev
    namespace: nlx
    user: arn:aws:eks:XXX:XXX:cluster/d-dev
  name: del/d-dev
- context:
    cluster: k3d-del-local
    namespace: default
    user: admin@k3d-del-local
  name: del/local
current-context: del/local
kind: Config
preferences: {}
```

**Comment by Ramilito** [comment]
When does the error occur? Do you get the selection menu or is it after selecting?

<img width="598" alt="image" src="https://github.com/user-attachments/assets/dd38f523-eb8f-439b-a7a9-0cc64c19a223">

**Comment by Ramilito** [comment]
I'm not able to reproduce, this config file is working for me:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://127.0.0.1:49718
  name: colima/dev_podme
contexts:
- context:
    cluster: colima/dev_podme
    namespace: default
    user: admin@k3d-del-local
  name: del/local
current-context: del/local
kind: Config
preferences: {}
users:
- name: admin@k3d-del-local
  user:
    client-certificate-data: 
    client-key-data: 
```

**Comment by eshepelyuk** [comment]
Ok, then I stuck to `v1.x`

**Comment by Ramilito** [comment]
If you have time to help me debug it then we might make it work, for example, did you clear the cache under `$HOME/.kube/kubesess/cache`

**Comment by eshepelyuk** [comment]
> If you have time to help me debug it then we might make it work, for example, did you clear the cache under `$HOME/.kube/kubesess/cache`

1. I followed release notes and made all mentioned changes.
1. I don't know how else can I help to debug, since this config just doesn't work for me, if you have other ideas - let me know

**Comment by Ramilito** [comment]
I'm using the kube-rs client to parse the config files (official kubernetes client), the error you see is when verifying that the read was successful. The file that it's complaining about is according to the client not correct, could you try to remove some parts of it and check if it start working? It could also be that since we merge all of the files under .kube/ folder that there is some conflicting values?

So, if you could (backup the file first) try to modify the `home/iesh/.kube/kubectx` file and see if it starts working, maybe something like this?
Removed the dev cluster
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX
    server: https://0.0.0.0:37771
  name: k3d-del-local
contexts:
- context:
    cluster: k3d-del-local
    namespace: default
    user: admin@k3d-del-local
  name: del/local
current-context: del/local
kind: Config
preferences: {}
```


Also, could you check your KUBECONFIG env variable?
